// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7v0_0W0HOW3_aWg_net59kuO5W0L1KT4',
    appId: '1:533651138691:web:260e05ae42ad1c2c7b13b6',
    messagingSenderId: '533651138691',
    projectId: 'studentgrade-dd23e',
    authDomain: 'studentgrade-dd23e.firebaseapp.com',
    storageBucket: 'studentgrade-dd23e.firebasestorage.app',
    measurementId: 'G-DWD9LLLTBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB52Wc_Lp-PSHXRKs-10M_DKVaKdtjyefs',
    appId: '1:533651138691:android:59b07d606c59c16e7b13b6',
    messagingSenderId: '533651138691',
    projectId: 'studentgrade-dd23e',
    storageBucket: 'studentgrade-dd23e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBccwObF0evOOrVOKN77xlZz7tAyEkXXuo',
    appId: '1:533651138691:ios:aca569c2e88206907b13b6',
    messagingSenderId: '533651138691',
    projectId: 'studentgrade-dd23e',
    storageBucket: 'studentgrade-dd23e.firebasestorage.app',
    iosClientId: '533651138691-vbmmuig1mptcqjkls1osg6k7hbbqt3fn.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentGradeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBccwObF0evOOrVOKN77xlZz7tAyEkXXuo',
    appId: '1:533651138691:ios:aca569c2e88206907b13b6',
    messagingSenderId: '533651138691',
    projectId: 'studentgrade-dd23e',
    storageBucket: 'studentgrade-dd23e.firebasestorage.app',
    iosClientId: '533651138691-vbmmuig1mptcqjkls1osg6k7hbbqt3fn.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentGradeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7v0_0W0HOW3_aWg_net59kuO5W0L1KT4',
    appId: '1:533651138691:web:b42ea46b705eab237b13b6',
    messagingSenderId: '533651138691',
    projectId: 'studentgrade-dd23e',
    authDomain: 'studentgrade-dd23e.firebaseapp.com',
    storageBucket: 'studentgrade-dd23e.firebasestorage.app',
    measurementId: 'G-VTC172KG7W',
  );
}
